name: DevCard

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  devcard:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@3.1.0
        with:
          devcard_id: ${{ secrets.DEVCARD_ID }}
          commit_message: "chore: update devcard.svg"
          committer_name: "tduyng"
          committer_email: "tienduy.nguyen.dev@gmail.com"