name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - master
      
jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Update metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          filename: metrics.svg
          committer_message: "chore: update ${filename}"
          config_timezone: Europe/Paris
          template: classic
          base: header, activity, community, repositories, metadata
          config_order: base.header, base.repositories, base.activity+community, isocalendar, music
          output_condition: skip-if-only-metadata-changed
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot, vba, tsql, scss, gherkin, vim, vim script, handlebars, XSLT
          # extras_js: |
          #   document.querySelector(".field.calendar")?.remove()
          #   document.querySelector(".field.diskUsage")?.remove()
          # plugin_isocalendar: yes
          # plugin_followup: yes
          # plugin_stargazers: yes
          # plugin_topics: yes
          # plugin_people: yes
          # plugin_people_types: followers

  delete-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 2
          keep_minimum_runs: 2