name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Update metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_message: Update ${filename}
          template: classic
          base: header, activity, community, repositories, metadata
          config_order: base.header, base.repositories, base.activity+community, isocalendar, music
          config_timezone: Australia/Sydney
          extras_js: |
            document.querySelector(".field.calendar")?.remove()
            document.querySelector(".field.diskUsage")?.remove()
          output_condition: skip-if-only-metadata-changed     
  delete-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 2
          keep_minimum_runs: 2